data: 
  train_dir:  ../paddy-disease-classification/train/
  val_dir:  ../paddy-disease-classification/validation/
  test_dir:  ../paddy-disease-classification/validation/
  augment: False

model: 
  feat_extractor: vit
  batch_size: 32
  train_bs: 32 
  valid_bs: 32
  epochs: 20
  heatmap_path: ../paddy/heatmaps/vit/
  # checkpoint: /home2/rishabh.s/ADS_NON_ADS_Classifier/model/best_combined.pth.tar

arch: 
  vit: 
    class: vit_with_cls_head
    args: 
      pretrained: 'google/vit-base-patch16-224-in21k'
      feature_dim: 768
      num_classes: 10
      dropout_prob: 0.4
      is_trainable: True
    
  convnext: 
    class: convnext_with_cls_head
    args: 
      pretrained: facebook/convnext-base-224-22k
      feature_dim: 1024
      num_classes: 10
      dropout_prob: 0.3
      is_trainable: True
    
  blipv2:
    class: blipv2_with_cls_head
    args: 
      pretrained: "blip2_feature_extractor"
      feature_dim: 768
      num_classes: 10
      dropout_prob: 0.3
      is_trainable: True

lr: 
  feat_ext_lr: 0.0001
  base_lr : 0.001
  T_0: 150
  eta_min: 0.00001


ckpt: 
  ckpt_frequency: 1
  ckpt_folder: ../paddy/checkpoints

wandb: 
  wandb_log: True
  sweep: False
  sweep_runs: 9
  sweep_id: rakshithart177/Paddy/nsunuq85
  project: Paddy
  entity: rakshithart177
  run_name: Vit_paddy

